# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utility_update.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14utility_update.proto\x12\x06Jingle\"\x9d\x01\n\x0eUtilityMessage\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x02\x12\r\n\x05\x61lloc\x18\x03 \x01(\x02\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\r\n\x05sigma\x18\x05 \x01(\x02\x12\x18\n\x10\x65vent_start_time\x18\x06 \x01(\x01\x12\x16\n\x0e\x65vent_end_time\x18\x07 \x01(\x01\x12\r\n\x05\x64\x65\x62ug\x18\x08 \x01(\t\"\x1d\n\nUtilityAck\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x32R\n\x10UtilityMessaging\x12>\n\x0ePublishUtility\x12\x16.Jingle.UtilityMessage\x1a\x12.Jingle.UtilityAck\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utility_update_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UTILITYMESSAGE._serialized_start=33
  _UTILITYMESSAGE._serialized_end=190
  _UTILITYACK._serialized_start=192
  _UTILITYACK._serialized_end=221
  _UTILITYMESSAGING._serialized_start=223
  _UTILITYMESSAGING._serialized_end=305
# @@protoc_insertion_point(module_scope)
